### ISSUE TITLE
Stackoverflow error when brewing beer

### ISSUE THREAD

**Issue by pvsmagbojos** [Lekavar/DrinkBeer-Forge1.17.1-#2]
Version: Minecraft 1.16.5
Mod Loader: Forge
Server Type: Mohist

Details:
Server crashes when trying to brew beer in a keg on the server, I've only tested this with the sweet berry beer recipe so far, but it has been consistent on both attempts. Haven't tried to replicate this bug in singleplayer, though it seems to crash only on the server's end, not on the client's end

Full Crash Report:
[crash-2021-11-22_10.34.03-server.txt](https://github.com/Lekavar/DrinkBeer-Forge1.17.1-/files/7580418/crash-2021-11-22_10.34.03-server.txt)
[crash-2021-11-22_10.40.13-server.txt](https://github.com/Lekavar/DrinkBeer-Forge1.17.1-/files/7580420/crash-2021-11-22_10.40.13-server.txt)

**Comment by MarbleGateKeeper** [comment]
It is a problem caused by **Polymorph (Forge)** mod.
This mod might implement some tweaks to RecipeManager which cause infinite looping. Recipe of brewing works normally without  **Polymorph (Forge)** . I advise you post an issue on the issue board of Polymorph mod.

**Comment by MarbleGateKeeper** [comment]
Currently I won't do any more work to investigate how Polymorph infinitely loop since I have some serious issue with my body. Once I'm ok I may do more investigation. Thanks for your feedback.

**Comment by MarbleGateKeeper** [comment]
I saw Polymorph has fixed it on newest version. So this issue now is closed.
